version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBMS_PASSWORD:-root}
      MYSQL_DATABASE: webmuasam
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  spring:
    build: .
    container_name: springboot
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      DBMS_USERNAME: ${DBMS_USERNAME:-root}
      DBMS_PASSWORD: ${DBMS_PASSWORD:-root}
      JWT_SIGNERKEY: ${JWT_SIGNERKEY:-supersecretkey}
      MAIL_USERNAME: ${MAIL_USERNAME:-youremail@gmail.com}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-yourmailpass}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      UPLOAD_DIR: /app/upload/
      MOMO_ACCESSKEY: ${MOMO_ACCESSKEY:-xxxxx}
      MOMO_SECRETKEY: ${MOMO_SECRETKEY:-yyyyy}
      MOMO_IPN_URL: ${MOMO_IPN_URL:-http://backend.yourdomain.com:8080/api/momo/ipn-handler}
      MOMO_RETURN_URL: ${MOMO_RETURN_URL:-http://frontend.yourdomain.com/}
    volumes:
      - /home/ubuntu/upload:/app/upload/

volumes:
  mysql_data:
  redis_data:
  upload_data:
