server:
  port: 8080



spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
        host: 192.168.1.9    # nếu Redis chạy trong Docker máy ảo
#        host: ${REDIS_HOST:redis}  # default 'redis' nếu biến môi trường không set
#        port: ${REDIS_PORT:6379}   #       host: ${REDIS_HOST}
        port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#
#  #upload file
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB
#jwt:
#  valid-duration: 7200 #in second
#  refreshable-duration : 604800 #in seconds

example:
  base-uri: file:///D:/JAVA/upload/

momo:
  partner-code : MOMO
  return-url: http://localhost:3000/
  end-point: https://test-payment.momo.vn/v2/gateway/api
  ipn-url: http://localhost:8080/api/momo/ipn-handler
#  ipn-url: ${MOMO_IPN_URL}
#  return-url: ${MOMO_RETURN_URL}
  request-type: captureWallet
